---
region: 'us-east-1'

component: 'test'

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

domain_name: "%{hiera('deployment_identifier')}-public.example"
private_domain_name: "%{hiera('deployment_identifier')}-private.example"

private_zone_vpc_id: 'vpc-a938ffc0'
private_zone_vpc_region: 'eu-west-2'
